export const MOCK_PROJECTS = [
  {
    id: 'proj-001',
    name: 'Example Project',
    client_name: '',
    description: 'A sample project to help you explore Shiplog. Edit or delete these tasks, or import your own to get started.',
    slug: 'example-project',
    created_at: '2026-05-01T09:00:00Z',
  },
]

export const MOCK_TASKS = {
  'proj-001': [
    {
      id: 'product-scope-and-prd',
      project_id: 'proj-001',
      title: 'Product scope and PRD',
      description: 'Define the core problem, intended user, and feature boundaries. Write the PRD covering all user flows, component structure, state shape, and acceptance criteria for Phase 1.',
      priority: 'critical',
      feature_area: 'Foundation',
      status: 'done',
      source: 'manual',
      notes: 'Scope limited to local state in Phase 1. Supabase backend deferred to Phase 2.',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'design-language-and-tokens',
      project_id: 'proj-001',
      title: 'Design language and tokens',
      description: 'Establish the visual direction: warm off-white palette, Syne and IBM Plex Mono type pairing, CSS variable system, and component-level rules for buttons, inputs, cards, and modals.',
      priority: 'high',
      feature_area: 'Foundation',
      status: 'done',
      source: 'manual',
      notes: '',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'projects-home-layout',
      project_id: 'proj-001',
      title: 'Projects home layout',
      description: 'Design the project grid, card hierarchy (client label, project name, description, task counts), hover states, empty state, delete confirmation, and New Project modal flow.',
      priority: 'high',
      feature_area: 'Projects',
      status: 'done',
      source: 'manual',
      notes: '',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'kanban-board-layout',
      project_id: 'proj-001',
      title: 'Kanban board layout',
      description: 'Design the three-column board: Backlog, In Progress, and Shipped. Define column headers with custom icons, card anatomy, drag-and-drop interaction model, feature area filter, and empty board state.',
      priority: 'high',
      feature_area: 'Board',
      status: 'done',
      source: 'manual',
      notes: 'Renamed columns from To Do / Done to Backlog / Shipped to better reflect UX team workflow.',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'task-management-modals',
      project_id: 'proj-001',
      title: 'Task management modals',
      description: 'Design the Add Task, Task Detail (view mode), and Edit Task (inline edit mode) modals. Define field set, priority and status selects, notes section, delete confirmation, and save behavior.',
      priority: 'medium',
      feature_area: 'Board',
      status: 'in_progress',
      source: 'manual',
      notes: '',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'import-and-export-flows',
      project_id: 'proj-001',
      title: 'Import and export flows',
      description: 'Design the JSON import modal with merge and replace modes, schema reference block, and LLM prompt helper for reformatting existing PRDs. Design the Jira CSV export scoped to shipped tasks.',
      priority: 'medium',
      feature_area: 'Board',
      status: 'in_progress',
      source: 'manual',
      notes: '',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'iconography-and-brand-mark',
      project_id: 'proj-001',
      title: 'Iconography and brand mark',
      description: 'Design the column icons (log, saw, ship) and the horizontal Shiplog lockup mark. Establish sizing, opacity, and placement rules for use in the header and column headers.',
      priority: 'low',
      feature_area: 'Foundation',
      status: 'todo',
      source: 'manual',
      notes: '',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
    {
      id: 'phase-2-auth-and-backend',
      project_id: 'proj-001',
      title: 'Phase 2: auth and backend',
      description: 'Define requirements for Supabase integration: schema design, row-level security, email authentication, real-time sync across users, and public read-only board URLs for client sharing.',
      priority: 'medium',
      feature_area: 'Foundation',
      status: 'todo',
      source: 'manual',
      notes: 'Separate PRD to be written once Phase 1 UI is validated.',
      created_at: '2026-05-01T09:00:00Z',
      updated_at: '2026-05-01T09:00:00Z',
    },
  ],
}
